[workspace]
members = [
    "day2",
    "day3",
    "day4",
    "day6",
    "day7",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.66"
thiserror = "1.0.37"
itertools = "0.10.5"
nom = "7.1.1"
petgraph = "0.6.2"
